// Generates lib/services/india_boundary_data.dart from Natural Earth's
// "India point of view" countries file (public domain):
//
//   curl -L -o /tmp/ne_ind.geojson https://raw.githubusercontent.com/nvkelso/\
//     natural-earth-vector/master/geojson/ne_10m_admin_0_countries_ind.geojson
//   dart run tool/india_boundary_data.dart /tmp/ne_ind.geojson
//
// Each sector is the stretch of India's outline, as India depicts it, between
// two anchor points; the closest polygon vertices to the anchors are used and
// the shorter way round the ring is taken. See lib/services/boundary_policy.dart.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

const _sectors = [
  // From the Punjab international border where the Jammu "working boundary"
  // begins, round Jammu & Kashmir, Gilgit-Baltistan, the Trans-Karakoram
  // tract and Aksai Chin, then down the Himachal Pradesh and Uttarakhand
  // border with Tibet to the Kali river at Dharchula on the Nepal border.
  (name: 'kashmir', start: (75.36, 32.33), end: (80.55, 29.85)),
  // The McMahon line, from the Bhutan tripoint to the Myanmar tripoint.
  (name: 'arunachal', start: (91.62, 27.82), end: (97.34, 28.22)),
];

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/india_boundary_data.dart <geojson>');
    exit(2);
  }
  final json =
      jsonDecode(File(args[0]).readAsStringSync()) as Map<String, dynamic>;
  final india = (json['features'] as List)
      .cast<Map<String, dynamic>>()
      .firstWhere(
        (f) => (f['properties'] as Map<String, dynamic>)['ADMIN'] == 'India',
      );
  final geometry = india['geometry'] as Map<String, dynamic>;
  final polygons = geometry['type'] == 'MultiPolygon'
      ? (geometry['coordinates'] as List).cast<List<dynamic>>()
      : [geometry['coordinates'] as List<dynamic>];
  // Mainland: the ring with the most vertices.
  var ring = polygons
      .map((p) => (p[0] as List).cast<List<dynamic>>())
      .reduce((a, b) => a.length >= b.length ? a : b)
      .map((p) => ((p[0] as num).toDouble(), (p[1] as num).toDouble()))
      .toList();
  if (ring.first == ring.last) ring = ring.sublist(0, ring.length - 1);

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/india_boundary_data.dart from Natural Earth',
    )
    ..writeln('// ne_10m_admin_0_countries_ind (public domain). Do not edit.')
    ..writeln('//')
    ..writeln(
      "// Stretches of India's outline as India depicts it, [lon, lat, ...].",
    )
    ..writeln('// ignore_for_file: prefer_single_quotes')
    ..writeln();
  for (final sector in _sectors) {
    final a = _nearest(ring, sector.start);
    final b = _nearest(ring, sector.end);
    final n = ring.length;
    final forward = (b - a + n) % n;
    final backward = (a - b + n) % n;
    final path = <(double, double)>[];
    if (forward <= backward) {
      for (var i = 0; i <= forward; i++) {
        path.add(ring[(a + i) % n]);
      }
    } else {
      for (var i = 0; i <= backward; i++) {
        path.add(ring[(a - i + n) % n]);
      }
    }
    stderr.writeln(
      '${sector.name}: ${path.length} vertices, '
      '${path.first} -> ${path.last}',
    );
    final id = sector.name[0].toUpperCase() + sector.name.substring(1);
    out.writeln('const List<double> kIndiaOutline$id = [');
    for (final (lon, lat) in path) {
      out.writeln('  ${lon.toStringAsFixed(5)}, ${lat.toStringAsFixed(5)},');
    }
    out.writeln('];');
    out.writeln();
  }
  File(
    'lib/services/india_boundary_data.dart',
  ).writeAsStringSync(out.toString());
}

int _nearest(List<(double, double)> ring, (double, double) p) {
  var best = 0;
  var bestD = double.infinity;
  for (var i = 0; i < ring.length; i++) {
    final dx = ring[i].$1 - p.$1, dy = ring[i].$2 - p.$2;
    final d = dx * dx + dy * dy;
    if (d < bestD) {
      bestD = d;
      best = i;
    }
  }
  stderr.writeln(
    '  anchor $p -> ${ring[best]} (${math.sqrt(bestD).toStringAsFixed(3)} deg)',
  );
  return best;
}
